version: '3'

services:
  square:
    build: ./square-service
    ports:
      - "5000:5000"
  cube:
    build: ./cube-service
    ports:
      - "5001:5000"
  fibonacci:
    build: ./fibonacci-service
    ports:
      - "5002:5000"
  ui:
    build: ./ui-service
    ports:
      - "80:80"
