version: '3.8'

services:
  square:
    build: ./square
    ports:
      - "5000:5000"

  cube:
    build: ./cube
    ports:
      - "5001:5000"

  ui:
    build: ./ui
    ports:
      - "8080:8080"
    depends_on:
      - square
      - cube
