version: '3'
services:
  square:
    build: ./square
    ports:
      - "5000:80"
  cube:
    build: ./cube
    ports:
      - "5001:80"
  ui:
    build: ./ui
    ports:
      - "5002:80"
    depends_on:
      - square
      - cube
